import type { ServiceListing } from '@/types/serviceListing';

export const SERVICE_EXAMPLE_LISTINGS: ServiceListing[] = [
  // House renting
  {
    id: 'house-1',
    serviceId: 'house-renting',
    title: 'Sunny 2BR apartment — downtown',
    description: 'Fully furnished, balcony, near metro. Water & Wi‑Fi included.',
    priceLabel: 'MMK 850,000 / month',
    location: 'Yangon · Bahan',
    tags: ['2 bed', 'Furnished', 'Pet friendly'],
    rating: 4.8,
    providerName: 'Golden Home Rentals',
    actionType: 'book',
    actionLabel: 'Book viewing',
  },
  {
    id: 'house-2',
    serviceId: 'house-renting',
    title: 'Family house with garden',
    description: 'Quiet street, 3 bedrooms, parking for 2 cars.',
    priceLabel: 'MMK 1,200,000 / month',
    location: 'Yangon · Mayangone',
    tags: ['3 bed', 'Garden', 'Parking'],
    rating: 4.6,
    providerName: 'CityNest Properties',
    actionType: 'book',
    actionLabel: 'Book viewing',
  },
  {
    id: 'house-3',
    serviceId: 'house-renting',
    title: 'Studio near university',
    description: 'Compact studio, ideal for students. 6‑month lease available.',
    priceLabel: 'MMK 380,000 / month',
    location: 'Mandalay · Chanmyathazi',
    tags: ['Studio', 'Short lease'],
    rating: 4.4,
    providerName: 'Campus Stays',
    actionType: 'book',
    actionLabel: 'Book viewing',
  },

  // Car renting
  {
    id: 'car-1',
    serviceId: 'car-renting',
    title: 'Toyota Vios 2022',
    description: 'Automatic, AC, Bluetooth. Free delivery within city.',
    priceLabel: 'MMK 45,000 / day',
    location: 'Yangon pickup',
    tags: ['Sedan', 'Automatic', 'Unlimited km'],
    rating: 4.9,
    providerName: 'DriveEasy Myanmar',
    actionType: 'book',
    actionLabel: 'Book car',
  },
  {
    id: 'car-2',
    serviceId: 'car-renting',
    title: 'Suzuki Ertiga 7-seater',
    description: 'Perfect for family trips. Child seat available on request.',
    priceLabel: 'MMK 65,000 / day',
    location: 'Yangon · Airport',
    tags: ['MPV', '7 seats', 'Airport pickup'],
    rating: 4.7,
    providerName: 'Family Wheels',
    actionType: 'book',
    actionLabel: 'Book car',
  },
  {
    id: 'car-3',
    serviceId: 'car-renting',
    title: 'Honda PCX scooter',
    description: 'Helmet included. Ideal for city errands.',
    priceLabel: 'MMK 12,000 / day',
    location: 'Mandalay downtown',
    tags: ['Scooter', 'Helmet included'],
    rating: 4.5,
    providerName: 'QuickRide Rentals',
    actionType: 'book',
    actionLabel: 'Book car',
  },

  // Delivery
  {
    id: 'delivery-1',
    serviceId: 'delivery',
    title: 'Same-day parcel (intra-city)',
    description: 'Pick up within 2 hours, deliver same day. Up to 5 kg.',
    priceLabel: 'From MMK 3,500',
    location: 'Yangon',
    tags: ['Same day', 'Up to 5 kg'],
    rating: 4.8,
    providerName: 'SwiftBox Delivery',
    actionType: 'request',
    actionLabel: 'Request delivery',
  },
  {
    id: 'delivery-2',
    serviceId: 'delivery',
    title: 'Food & grocery express',
    description: 'Temperature-controlled bags. Live tracking on map.',
    priceLabel: 'From MMK 2,500',
    location: 'Yangon · Mandalay',
    tags: ['Food safe', 'Live tracking'],
    rating: 4.6,
    providerName: 'FreshRun',
    actionType: 'request',
    actionLabel: 'Request delivery',
  },
  {
    id: 'delivery-3',
    serviceId: 'delivery',
    title: 'Bulk business delivery',
    description: 'Multi-stop routes for shops. Optimized daily runs.',
    priceLabel: 'Custom quote',
    location: 'Nationwide',
    tags: ['B2B', 'Multi-stop'],
    rating: 4.9,
    providerName: 'LogiLink Myanmar',
    actionType: 'request',
    actionLabel: 'Request quote',
  },

  // Laundry
  {
    id: 'laundry-1',
    serviceId: 'laundry',
    title: 'Wash & fold — 5 kg bag',
    description: 'Pickup and return within 24 hours. Eco detergent.',
    priceLabel: 'MMK 8,000',
    location: 'Yangon',
    tags: ['24h turnaround', 'Pickup included'],
    rating: 4.7,
    providerName: 'CleanFold Co.',
    actionType: 'call',
    actionLabel: 'Call to book',
  },
  {
    id: 'laundry-2',
    serviceId: 'laundry',
    title: 'Dry clean — suit or dress',
    description: 'Professional press and stain treatment.',
    priceLabel: 'MMK 12,000 / item',
    location: 'Yangon · Bahan',
    tags: ['Dry clean', 'Express 6h'],
    rating: 4.8,
    providerName: 'Prestige Laundry',
    actionType: 'call',
    actionLabel: 'Call to book',
  },
  {
    id: 'laundry-3',
    serviceId: 'laundry',
    title: 'Monthly family plan',
    description: '2 pickups per week, up to 20 kg. Best for households.',
    priceLabel: 'MMK 120,000 / month',
    location: 'Yangon',
    tags: ['Subscription', '20 kg/week'],
    rating: 4.5,
    providerName: 'HomeFresh Laundry',
    actionType: 'call',
    actionLabel: 'Call to book',
  },

  // Plumbing
  {
    id: 'plumbing-1',
    serviceId: 'plumbing',
    title: 'Emergency leak repair',
    description: '24/7 call-out. Pipe burst, tap leak, toilet overflow.',
    priceLabel: 'From MMK 25,000',
    location: 'Yangon',
    tags: ['24/7', 'Emergency'],
    rating: 4.9,
    providerName: 'AquaFix Plumbing',
    actionType: 'call',
    actionLabel: 'Call plumber',
  },
  {
    id: 'plumbing-2',
    serviceId: 'plumbing',
    title: 'Bathroom installation',
    description: 'Full bathroom fitting — tiles, pipes, fixtures.',
    priceLabel: 'Free estimate',
    location: 'Yangon · Mandalay',
    tags: ['Installation', 'Licensed'],
    rating: 4.7,
    providerName: 'ProPipe Services',
    actionType: 'call',
    actionLabel: 'Call for estimate',
  },
  {
    id: 'plumbing-3',
    serviceId: 'plumbing',
    title: 'Water heater service',
    description: 'Repair or replace electric and gas heaters.',
    priceLabel: 'From MMK 35,000',
    location: 'Yangon',
    tags: ['Repair', 'Replacement'],
    rating: 4.6,
    providerName: 'HeatFlow Plumbing',
    actionType: 'call',
    actionLabel: 'Call plumber',
  },

  // Air con
  {
    id: 'aircon-1',
    serviceId: 'aircon',
    title: 'AC general service (1 unit)',
    description: 'Deep clean, gas check, filter wash. All brands.',
    priceLabel: 'MMK 18,000',
    location: 'Yangon',
    tags: ['All brands', '1–2h service'],
    rating: 4.8,
    providerName: 'CoolAir Myanmar',
    actionType: 'call',
    actionLabel: 'Call technician',
  },
  {
    id: 'aircon-2',
    serviceId: 'aircon',
    title: 'Split AC installation',
    description: 'Includes bracket, piping up to 3 m, vacuum and test.',
    priceLabel: 'From MMK 85,000',
    location: 'Yangon · Naypyidaw',
    tags: ['Installation', 'Warranty'],
    rating: 4.7,
    providerName: 'Arctic Install Co.',
    actionType: 'call',
    actionLabel: 'Call for install',
  },
  {
    id: 'aircon-3',
    serviceId: 'aircon',
    title: 'Annual maintenance plan',
    description: '4 visits per year for up to 2 units. Priority booking.',
    priceLabel: 'MMK 150,000 / year',
    location: 'Yangon',
    tags: ['Annual plan', '2 units'],
    rating: 4.9,
    providerName: 'ChillCare Services',
    actionType: 'call',
    actionLabel: 'Call to subscribe',
  },

  // Electronics
  {
    id: 'electronics-1',
    serviceId: 'electronics',
    title: 'TV repair — no picture / sound',
    description: 'Home visit diagnosis. LED, OLED, and smart TVs.',
    priceLabel: 'From MMK 20,000',
    location: 'Yangon',
    tags: ['Home visit', 'All TV types'],
    rating: 4.6,
    providerName: 'ScreenFix Electronics',
    actionType: 'call',
    actionLabel: 'Call technician',
  },
  {
    id: 'electronics-2',
    serviceId: 'electronics',
    title: 'Phone screen replacement',
    description: 'iPhone and Samsung. Genuine-grade parts, 3‑month warranty.',
    priceLabel: 'From MMK 45,000',
    location: 'Yangon · Mandalay',
    tags: ['Same day', 'Warranty'],
    rating: 4.8,
    providerName: 'MobileCare Pro',
    actionType: 'call',
    actionLabel: 'Call to repair',
  },
  {
    id: 'electronics-3',
    serviceId: 'electronics',
    title: 'Washing machine repair',
    description: 'Not draining, noisy drum, error codes — we fix it.',
    priceLabel: 'From MMK 30,000',
    location: 'Yangon',
    tags: ['Home appliance', 'All brands'],
    rating: 4.5,
    providerName: 'Appliance Doctor',
    actionType: 'call',
    actionLabel: 'Call technician',
  },

  // Plants nursery
  {
    id: 'plants-1',
    serviceId: 'plants-nursery',
    title: 'Indoor plant starter set',
    description: 'Monstera, snake plant, and pothos in ceramic pots. Care guide included.',
    priceLabel: 'MMK 85,000 / set',
    location: 'Yangon · Kamayut',
    tags: ['Indoor', '3 plants', 'Pots included'],
    rating: 4.8,
    providerName: 'GreenLeaf Nursery',
    actionType: 'call',
    actionLabel: 'Call to order',
  },
  {
    id: 'plants-2',
    serviceId: 'plants-nursery',
    title: 'Garden saplings bundle',
    description: 'Tomato, chili, and herb saplings. Organic soil mix available.',
    priceLabel: 'From MMK 15,000',
    location: 'Yangon',
    tags: ['Outdoor', 'Edible garden', 'Bulk discount'],
    rating: 4.6,
    providerName: 'Yangon Growers',
    actionType: 'call',
    actionLabel: 'Call to order',
  },
  {
    id: 'plants-3',
    serviceId: 'plants-nursery',
    title: 'Office greenery package',
    description: 'Low-maintenance plants for desks and reception. Monthly maintenance optional.',
    priceLabel: 'From MMK 200,000',
    location: 'Yangon · Naypyidaw',
    tags: ['B2B', 'Maintenance plan'],
    rating: 4.9,
    providerName: 'Urban Roots Co.',
    actionType: 'call',
    actionLabel: 'Call for quote',
  },

  // Home cleaning
  {
    id: 'cleaning-1',
    serviceId: 'home-cleaning',
    title: 'Standard home clean (2BR)',
    description: 'Dusting, mopping, bathroom & kitchen. Supplies provided.',
    priceLabel: 'MMK 35,000 / visit',
    location: 'Yangon',
    tags: ['2–3h', 'Supplies included'],
    rating: 4.7,
    providerName: 'SparkleHome Cleaning',
    actionType: 'call',
    actionLabel: 'Call to book',
  },
  {
    id: 'cleaning-2',
    serviceId: 'home-cleaning',
    title: 'Deep clean — move-in / move-out',
    description: 'Inside cabinets, windows, appliances. Ideal before handover.',
    priceLabel: 'From MMK 75,000',
    location: 'Yangon · Mandalay',
    tags: ['Deep clean', 'Move-in/out'],
    rating: 4.8,
    providerName: 'FreshStart Maids',
    actionType: 'call',
    actionLabel: 'Call to book',
  },
  {
    id: 'cleaning-3',
    serviceId: 'home-cleaning',
    title: 'Weekly cleaning subscription',
    description: 'Same cleaner every week. 4 visits per month, flexible time slots.',
    priceLabel: 'MMK 120,000 / month',
    location: 'Yangon',
    tags: ['Weekly', 'Same cleaner'],
    rating: 4.6,
    providerName: 'TidyNest Services',
    actionType: 'call',
    actionLabel: 'Call to subscribe',
  },

  // Car wash
  {
    id: 'carwash-1',
    serviceId: 'car-wash',
    title: 'Exterior wash & dry',
    description: 'Hand wash, tire shine, windows. Sedan or hatchback.',
    priceLabel: 'MMK 8,000',
    location: 'Yangon · mobile',
    tags: ['30 min', 'We come to you'],
    rating: 4.5,
    providerName: 'ShineOn Mobile Wash',
    actionType: 'book',
    actionLabel: 'Book wash',
  },
  {
    id: 'carwash-2',
    serviceId: 'car-wash',
    title: 'Full detail — interior & exterior',
    description: 'Vacuum, dashboard polish, wax, engine bay wipe.',
    priceLabel: 'MMK 45,000',
    location: 'Yangon',
    tags: ['Full detail', '3–4h'],
    rating: 4.9,
    providerName: 'ProDetail Myanmar',
    actionType: 'book',
    actionLabel: 'Book detail',
  },
  {
    id: 'carwash-3',
    serviceId: 'car-wash',
    title: 'SUV / van wash package',
    description: 'Larger vehicle wash with undercarriage rinse.',
    priceLabel: 'MMK 15,000',
    location: 'Yangon · Mandalay',
    tags: ['SUV', 'Van', 'Undercarriage'],
    rating: 4.6,
    providerName: 'BigRide Car Care',
    actionType: 'book',
    actionLabel: 'Book wash',
  },

  // Dog spa
  {
    id: 'dogspa-1',
    serviceId: 'dog-spa',
    title: 'Bath & brush — small breed',
    description: 'Gentle shampoo, blow dry, ear clean. Up to 10 kg.',
    priceLabel: 'MMK 25,000',
    location: 'Yangon · Bahan',
    tags: ['Small breed', '45 min'],
    rating: 4.8,
    providerName: 'Paws & Relax Spa',
    actionType: 'book',
    actionLabel: 'Book appointment',
  },
  {
    id: 'dogspa-2',
    serviceId: 'dog-spa',
    title: 'Full groom — cut & style',
    description: 'Breed-specific cut, nail trim, sanitary trim, cologne.',
    priceLabel: 'From MMK 45,000',
    location: 'Yangon',
    tags: ['Grooming', 'Nail trim'],
    rating: 4.9,
    providerName: 'Happy Tails Grooming',
    actionType: 'book',
    actionLabel: 'Book groom',
  },
  {
    id: 'dogspa-3',
    serviceId: 'dog-spa',
    title: 'Spa day package',
    description: 'Bath, massage, blueberry facial, paw balm. Medium breeds.',
    priceLabel: 'MMK 55,000',
    location: 'Yangon',
    tags: ['Spa package', 'Medium breed'],
    rating: 4.7,
    providerName: 'Luxury Paws Studio',
    actionType: 'book',
    actionLabel: 'Book spa day',
  },
];

export function getListingsForService(serviceId: string): ServiceListing[] {
  return SERVICE_EXAMPLE_LISTINGS.filter((listing) => listing.serviceId === serviceId);
}
